### ISSUE TITLE
MIT licence removed from copied code

### ISSUE THREAD

**Issue by peppy** [KindRedSand/Terraria.ModKit#10]
Hey,

Noticed you were using our framework but have renamed it and removed the MIT licence. Probably not great.

**Comment by KindRedSand** [comment]
Hello.
Long story short: I used osu.Framework for self education long time ago, reusing parts of code in order to learn c# and understand how things work. In this process i rewrite code around concepts what i use when start learning cpp and SFML, and in order to not get confused with own code this project, where parts of your code reused, are named differently, and bc atm i was still a kid i don't bother myself with licenses. I sometimes reuse this old code in order to quickly make things, like in this case.
For new project what i joined we making our own library from scratch. 

Rn i don't have enough time to even update this to latest version so if you insist i can delete this whole repo, as i already done with other where parts of this code are encountered.

By the way, thank you for your work!

**Comment by peppy** [comment]
It's not a big deal, just noticed in passing. At very least you should include the original licence in some file somewhere in your repo.
